name: Generate decks
on: 
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  all-decks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone bibixx/zdaj-se-pjatk-data repository
        run: git clone --depth 1 https://github.com/bibixx/zdaj-se-pjatk-data
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Restore project
        run: dotnet restore
      - name: Run deck generation script
        run: dotnet fsi ./scripts/Generate.fsx
        env:
          DATA_REPOSITORY_PATH: zdaj-se-pjatk-data
      - name: Upload generated decks
        uses: actions/upload-artifact@v4
        with:
          name: generated-decks
          path: |
            zdajse-collections 